### ISSUE TITLE
Build and Deployment pipeline - Factor deployment steps out into a reusable workflow.

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-audit#29]
The [Build and Deploy Audit Image](https://github.com/bcgov/von-bc-registries-audit/blob/a5e95392b91b099c9b1c650ec40153ad8e56f7f9/.github/workflows/main.yml) workflow defines a number of deployment jobs which are basically identical.  This introduces an undesirable amount of code duplication.  As it stands, if the steps for a given job need to be changed, they would need to be changed in three places.

Task:
Factor out the deployment steps into a reusable workflow and then utilize the new workflow in place of the duplicate code for each of the deployment jobs.  This will eliminate the unnecessary code duplication, simplifying the workflows making them easier to read, and far easier to maintain in the future.

TIP:
While performing the refactoring you will need to define the [`environment`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment) using an [env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenv) (environment) variable so the value can also be passed into the reusable workflow to be used for the image tags and notifications.

Examples of reusable workflows:
- https://github.com/hyperledger/aries-cloudagent-python/blob/main/.github/workflows/tests-indy.yml
- https://github.com/hyperledger/indy-node/blob/main/.github/workflows/reuseable_test.yaml
- https://github.com/hyperledger/indy-shared-gha/blob/main/.github/workflows/buildimage.yaml
- https://github.com/hyperledger/indy-shared-gha/blob/main/.github/workflows/buildpackages.yaml
- https://github.com/hyperledger/indy-shared-gha/blob/main/.github/workflows/publish_artifacts.yaml

Examples of calling reusable workflows:
- https://github.com/hyperledger/aries-cloudagent-python/blob/main/.github/workflows/pr-tests.yml#L14-L20
- https://github.com/hyperledger/indy-node/blob/main/.github/workflows/PR.yaml#L71-L77
- https://github.com/hyperledger/indy-node/blob/main/.github/workflows/PR.yaml#L51-L58
- https://github.com/hyperledger/indy-node/blob/main/.github/workflows/PR.yaml#L60-L69
- https://github.com/hyperledger/indy-node/blob/main/.github/workflows/Push.yaml#L66-L78

Acceptance Criteria:
- The deployment steps, including Rocket.Chat notification, are factored out into a reusable workflow.
- The reusable workflow is parameterized in such a way as to make it generic.  i.e. It could be used to deploy an arbitrary image from an arbitrary GHCR into an arbitrary OpenShift namespace, using an arbitrary tag.
- The deployment jobs are updated to utilize the reusable workflow in place of the duplicate code.
- The values (image urls for example) used in the `Build and Deploy Audit Image` are parameterized to eliminate duplication of statically defined strings.  For example, the path to the GHCR for the images can be dynamically determined using variables in GHA.
- The `Build and Deploy Audit Image` workflow retains it's original functionality.

**Comment by rajpalc7** [comment]
Made the changes that wade suggested during the demo on Wednesday.  Will move this ticket to Review/QA now to demo it on Tuesday once wade is back from vacation

**Comment by rajpalc7** [comment]
Ticket is completed now. Ready for demo today
