### ISSUE TITLE
Build and Deployment pipeline - Limit workflow runs to the main repo so it will not try to run on a fork

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-audit#31]
The [Build and Deploy Audit Image](https://github.com/bcgov/von-bc-registries-audit/blob/a5e95392b91b099c9b1c650ec40153ad8e56f7f9/.github/workflows/main.yml) workflow is not limited to executing on a fork.  If it were to execute on another fork it would fail since the fork will not (and should never have) the secrets necessary for it to execute successfully.  Therefore the workflow should be limited to only run from the main repository where the necessary secrets are available.

Task:
Update the workflow with a conditional statement to ensure it will only run when executed from the main repository where the necessary secrets are defined.

Example:
- https://github.com/hyperledger/aries-cloudagent-python/blob/421c4ed6a3f750c7f30af7b85d1481a762a5acc4/.github/workflows/nightly-tests.yml#L10

Acceptance Criteria:
- The workflow will only execute on the main repository and it will not execute on any other fork.

**Comment by WadeBarnes** [comment]
@cvarjao, @rajpalc7, here is another enhancement or the workflow.

**Comment by rajpalc7** [comment]
Ticket is completed now. Ready for demo today
