### ISSUE TITLE
Add pipelines to automate the CI/CD processes on OpenShift

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-audit#9]
Create a CI/CD pipeline. Options include GitHub Actions, Tekton, ArgoCD, etc. We are starting with this project because it is a fairly simple pipeline. The technology and patterns developed here will then be applied to our other projects so we can incrementally retire Jenkins.

**Comment by WadeBarnes** [comment]
@rajpalc7, I'm thinking, since this project is so small (just a single container), that it would be a great project to use to evaluate each technology by developing an end-to-end pipeline for it using each.  This would also be a great learning experience for you.  What are you thoughts?

**Comment by WadeBarnes** [comment]
To focus on a simple GitHub Pipeline to start.  Related WIP PR; https://github.com/bcgov/von-bc-registries-audit/pulls

**Comment by WadeBarnes** [comment]
Flow diagrams for discussion:

## Commit workflow:
```mermaid
flowchart 
    Commit(Commit)
    Build(Build Image)
    Publish(Publish to gcr)
    Tag(Tag latest, dev)
    Deploy(Deploy to OCP Dev environment)
    Watch(Monitor Rollout)
    Notify(Notify of any Success/Failure)

    Commit-->Build
    Build-->Publish
    Publish-->Tag
    Tag-->Deploy
    Deploy-->Watch
    Watch-->Notify
```

## Manual Trigger (workflow_dispatch) - Deploy to `test`:
```mermaid
flowchart 
    Trigger(Deploy to Test - workflow_dispatch)
    Tag(Tag image tagged as dev to test)
    Deploy(Deploy to OCP test environment)
    Watch(Monitor Rollout)
    Notify(Notify of any Success/Failure)

    Trigger-->Tag
    Tag-->Deploy
    Deploy-->Watch
    Watch-->Notify
```

## Prerelease Trigger - Deploy to `test`:
```mermaid
flowchart 
    Prerelease(Publish new pre-release)
    Tag(Tag image with matching sha to test)
    Deploy(Deploy to OCP test environment)
    Watch(Monitor Rollout)
    Notify(Notify of any Success/Failure)

    Prerelease-->Tag
    Tag-->Deploy
    Deploy-->Watch
    Watch-->Notify
```

## Release Trigger - Deploy to `prod`:
```mermaid
flowchart 
    Release(Publish new release)
    Backup(Tag current prod image as backup)
    Tag(Tag image with matching sha to prod)
    Deploy(Deploy to OCP test environment)
    Watch(Monitor Rollout)
    Notify(Notify of any Success/Failure)

    Release-->Backup
    Backup-->Tag
    Tag-->Deploy
    Deploy-->Watch
    Watch-->Notify
```

## Rollback workflow

 - TDB 
 
 ## PR Workflow
 
 - Next steps
 - PR based pipeline flow.  Similar to `Commit`, but deploys a named instance into the `dev` environment.  The instance is destroyed when the PR is closed (merged or rejected).

**Comment by WadeBarnes** [comment]
One issue we've seen that needs to be overcome is the speed at which OCP detects changes to the tags on images it is watching in the `gcr`.  Typically image streams refresh their images every fifteen minutes.  Other teams have gotten around this by deleting and recreating the associated image stream(s) whenever an image is tagged.  Wondering if there is a more elegant way.

**Comment by hiteshgh** [comment]
clecio helping Raj

**Comment by rajpalc7** [comment]
Met Clecio yesterday and made some good progress on the ticket.
Demoed CICD GHA pipeline to Wade this morning. 

His suggestion is as follows - When initially building the image make sure you include latest as a tag. Then tag the image in the ghcr for the environment, dev for example, before pulling the image and pushing it to OCP. That way it's clear which images have been tagged and deployed to a given environment when looking at them in either the ghrc or OCP. Much easier than tracking down the sha.

**Comment by cvarjao** [comment]
You can also tag the image in GCR with an environment tag, but I strongly suggest that the image sha reference remains the one being used under the cover to move the image across environments.

**Comment by hiteshgh** [comment]
Done with Dev, Test, PROD pending

**Comment by rajpalc7** [comment]
Looking forward to demo it to Wade on Tuesday, once he is back.

**Comment by WadeBarnes** [comment]
Initial build and deployment pipeline addressed with https://github.com/bcgov/von-bc-registries-audit/pull/25
